version: 1
from: "infracamp/kickstart-flavor-gaia"

apache_fallback_resource: "/index.php"

command:
  build:
    - "composer update"

  build_docs:
    - "sudo apt-get install wget && cd /opt/docs && cp /opt/README.md /opt/docs/index.md && wget --recursive --no-clobber --page-requisites --html-extension --convert-links --restrict-file-names=windows --domains localhost --no-parent localhost"
