version: 1
from: "infracamp/kickstart-flavor-gaia"

apache_fallback_resource: "/index.php"

command:
  build:
    - "composer update"

  build_docs:
    - "cd /opt/docs && wget --recursive --no-clobber --page-requisites --html-extension --convert-links --restrict-file-names=windows --domains localhost --no-parent localhost"
